vaadin/cookbook

frontend/recipe/geo-location/geo-location.ts

The recipe shows how to get the current position of the user, and watch it as it changes over time.

add a 'geo-location' recipe

---

frontend/recipe/geo-location/geo-location.ts
frontend/recipe/leaflet-map/leaflet-map.ts
package.json

The recipe shows how to show a map using the Leaflet library.

add a 'leaflet-map' recipe 

---

src/main/java/com/vaadin/recipes/AppShell.java
src/main/java/com/vaadin/recipes/Application.java
src/main/java/com/vaadin/recipes/recipe/longrunningtask/BackendService.java
src/main/java/com/vaadin/recipes/recipe/longrunningtask/LongRunningTask.java

How do I show a progress indicator while performing a long-running task

Fixes #46 How do I show a progress indicator while performing a long running task

---

src/main/java/com/vaadin/recipes/recipe/popupbutton/ButtonPopupPositionView.java

Implements show a popup next to a button when it is clicked.

Show a popup next to a button when it is clicked

---

frontend/recipe/treegridsubtreehighlight/treegrid-subtree-highlight.css
src/main/java/com/vaadin/recipes/recipe/treegridsubtreehighlight/Department.java
src/main/java/com/vaadin/recipes/recipe/treegridsubtreehighlight/DepartmentData.java
src/main/java/com/vaadin/recipes/recipe/treegridsubtreehighlight/TreeGridSubTreeHighlight.java

Fixes https://github.com/vaadin/cookbook/issues/69

How do I highlight children of the selected parent node in TreeGrid

---

src/main/java/com/vaadin/recipes/recipe/griddndreorderrows/GridDndReorderRows.java

Recipe for drag'n'drop reordering a Grid

drag'n'drop reorder a grid

---

src/main/java/com/vaadin/recipes/AppShell.java
src/main/java/com/vaadin/recipes/data/AllRecipes.java
src/main/java/com/vaadin/recipes/recipe/allowusertopickacolor/AllowUserToPickAColor.java
src/main/java/com/vaadin/recipes/recipe/dynamicallychangeprogressbarcolor/DynamicallyChangeProgressBarColor.java

Make sure all Java recipes extend Recipe

Fix title setting for TabsWithRoutes

---

src/main/java/com/vaadin/recipes/recipe/tabsheet/TabSheetView.java

An example of creating a TabSheet

---

frontend/recipe/copytoclipboard/copytoclipboard.js
src/main/java/com/vaadin/recipes/recipe/copytoclipboard/CopyToClipboard.java

Copy to clipboard recipe

---

frontend/views/recipes-list-view.ts
package.json
parseClientRoutes.ts
pnpm-lock.yaml
src/main/java/com/vaadin/recipes/recipe/Tag.java
src/main/java/com/vaadin/recipes/recipe/gridcsvexport/GridCsvExport.java

Missing logic:
- Render a checkbox for the available tags (instead of the hardcoded list)
- Update tag count tags when the search filter is modified

Tag filter

---

src/main/java/com/vaadin/recipes/recipe/camera/CameraView.java

Fix the bug for the photo preview
Update the comment to change the upload size value
Remove the old preview if you take a second photo.
I can't test on iphone since the simulator doesn't have a camera :). But the preview should be better

Fix the bug for the photo preview

---

src/main/java/com/vaadin/recipes/recipe/editablelabel/EditableLabel.java
src/main/java/com/vaadin/recipes/recipe/editablelabelondblclick/EditableLabelOnDblClick.java

Create an editable Label on double-click

---

frontend/recipe/client-side-view-displaying-live-data/client-side-view-displaying-live-data.ts
parseClientRoutes.ts
src/main/java/com/vaadin/recipes/recipe/clientsidelivedata/StockDataEndpoint.java

A client-side example for showing real-time data

Live data TS

---

src/main/java/com/vaadin/recipes/recipe/alwayseditablelabel/AlwaysEditableLabel.java

Create a Label component that is always in editable mode

---

frontend/recipe/visiblyclicked/visiblyclicked.css
src/main/java/com/vaadin/recipes/recipe/visiblyclicked/VisiblyClicked.java

visibly-clicked-button

---

frontend/recipe/dynamic-combobox-item-background-color/vaadin-combo-box-item-styles.css
src/main/java/com/vaadin/recipes/recipe/dynamiccomboboxitembackgroundcolor/DynamicComboboxItemBackgroundColor.java

Enable dynamic setting of ComboBox items' background color

---

frontend/recipe/reduce-combobox-items-separation/vaadin-combo-box-item-styles.css
src/main/java/com/vaadin/recipes/recipe/reducecomboboxitemsseparation/ReduceComboBoxItemsSeparation.java

Enable reduced spacing between ComboBox items

---

src/main/java/com/vaadin/recipes/recipe/recursiveselecttree/RecursiveSelectTreeGrid.java
src/main/java/com/vaadin/recipes/recipe/recursiveselecttree/TreeGridRecursiveSelectionView.java

Add this cookbook recipe:
https://github.com/vaadin/cookbook/issues/133

Select recursively an item in a Treegrid

---

pom.xml
src/main/java/com/vaadin/recipes/recipe/displayversion/AppVersions.java
src/main/java/com/vaadin/recipes/recipe/displayversion/DisplayVersion.java
src/main/resources/application.properties
src/main/resources/com/vaadin/recipes/recipe/displayversion/application.properties

Created example of using Spring Boot application.properties and Maven build to automatically expand project, Vaadin and Java versions and build time into properties and display in UI.

Display versions

---

pom.xml
src/main/java/com/vaadin/recipes/recipe/displayversion/AppVersions.java
src/main/java/com/vaadin/recipes/recipe/displayversion/DisplayVersion.java
src/main/resources/com/vaadin/recipes/recipe/displayversion/pom.xml

Multiple fixes to make this meaningful and copypasteable:
- Add: pom.xml example
- Fix: Component to Configuration
- Fix: Javadocs
- Fix: Unfiltered application.properties as example
- Change: Use TextArea instead of Text

Updated the display version information

---

frontend/recipe/densegrid/densegrid.css
src/main/java/com/vaadin/recipes/recipe/densegrid/GridDenseTheme.java

The default compact theme is still containing a lot of padding

Add a recipe "Dense grid theme"

---

frontend/recipe/distinguisheditablefromnoneditablecells/distinguish-editable-from-non-editable-cells.css
src/main/java/com/vaadin/recipes/recipe/distinguisheditablefromnoneditablecells/DistinguishEditableFromNonEditableCells.java

Luis inspired me to create a recipe so I did :-)

Distinguish editable cells from non editable cells using GridPro.

---

frontend/recipe/grid-item-specific-drop-locations/grid-drop-locations.css
src/main/java/com/vaadin/recipes/recipe/griditemspecificdroplocations/GridItemSpecificDropLocations.java

Related to https://github.com/vaadin/vaadin-grid/issues/2102

Defining item specific drop locations for Grid

---

frontend/views/recipes-list-view.ts
parseClientRoutes.ts
src/main/java/com/vaadin/recipes/data/RecipeInfo.java
src/main/java/com/vaadin/recipes/recipe/Tag.java

Add Flow/Fusion tag automatically in addition to Java/TS

---

frontend/recipe/print-selectively/shared-styles.css
src/main/java/com/vaadin/recipes/recipe/printselectively/PrintSelectively.java

Allow selective printing of components

---

src/main/java/com/vaadin/recipes/recipe/gridtemplaterendererinteraction/GridTemplateRendererInteraction.java

create a recipe for using a template renderer in grid and add two ways communication with event handler and javascript call

create code for using template renderer in grid and interact with it

---

src/main/java/com/vaadin/recipes/recipe/densegrid/GridDenseTheme.java

Add a link to the css to the dense grid

Add a link to the css to the dense grid

---

src/main/java/com/vaadin/recipes/recipe/customlayout/CustomLayout.java

See https://github.com/vaadin/cookbook/pull/158#issuecomment-888255579

Add guard to CustomLayout JS expression

---

frontend/recipe/grid-arrow-selection/vaadin-grid-styles.css
src/main/java/com/vaadin/recipes/recipe/gridarrowselection/GridArrowSelection.java

Closes  #186.
Allow Grid rows to be selected using up/down arrow keys

Allow Grid rows to be selected using up/down arrow keys

---

frontend/index.html

Integrates HaaSv2 and Antlers next

#207: uses HaaSv2 and Antlers next

---

frontend/code-viewer.ts

Remove meta info from rendered Java code

---

src/main/java/com/vaadin/recipes/recipe/treegridwithicons/FileItem.java
src/main/java/com/vaadin/recipes/recipe/treegridwithicons/FileItemData.java
src/main/java/com/vaadin/recipes/recipe/treegridwithicons/TreeGridWithIcons.java

Add a recipe of TreeGrid with a TemplateRenderer for displaying custom icons in the hierarchy column, as described in
https://vaadin.com/forum/thread/17625675/treegrid-displaying-icon-for-hierachy-column

Add TreeGrid with icons in hierarchy column

---

frontend/code-viewer.ts

Remove extra empty lines due to the removal of the recipe imports and `@Metadata`

Improve code sanitization

---

.github/workflows/validation.yml
.gitpod.Dockerfile
Dockerfile
pom.xml

There is no Trava version for Java 17 yet: https://github.com/TravaOpenJDK/trava-jdk-11-dcevm/issues/52

Use Java 17

---

frontend/recipe/dialog-slide-in-out/vaadin-dialog-overlay-styles.css
src/main/java/com/vaadin/recipes/recipe/dialogslideinout/DialogSlideInOut.java

Example of how to change the dialog's default theme from fade in/out to slide in/out.

Dialog slide in and out animation

---

frontend/views/recipes-list-view.ts

Delete unnecessary z-indexes

---

src/main/java/com/vaadin/recipes/recipe/uieventbus/UIEventBusRecipe.java

chore: use the UI from the AttachEvent

---

src/main/java/com/vaadin/recipes/recipe/gridexternaltemplaterenderer/GridExternalTemplateRenderer.java

fix link to js file with renderer in annotation

---

src/main/java/com/vaadin/recipes/recipe/contextmenuassingleselect/ContextMenuAsSingleSelect.java
src/main/java/com/vaadin/recipes/recipe/displayversion/DisplayVersion.java
src/main/java/com/vaadin/recipes/recipe/gridcsvexport/GridCsvExport.java
src/main/java/com/vaadin/recipes/recipe/griddetailstable/MonthlyExpense.java
src/main/java/com/vaadin/recipes/recipe/griddrilldown/GridDrillDown.java
src/main/java/com/vaadin/recipes/recipe/gridexcellikecellselection/GridExcelLikeCellSelection.java
src/main/java/com/vaadin/recipes/recipe/gridscrolllistener/GridScrollListener.java
src/main/java/com/vaadin/recipes/recipe/highlighrouterlinkwithdefaultroute/AboutView.java
src/main/java/com/vaadin/recipes/recipe/highlighrouterlinkwithdefaultroute/HighlightRouterLinkWithDefaultRoute.java
src/main/java/com/vaadin/recipes/recipe/highlighrouterlinkwithdefaultroute/HomeView.java
src/main/java/com/vaadin/recipes/recipe/livedata/LiveData.java
src/main/java/com/vaadin/recipes/recipe/scrollabledialog/ScrollableDialog.java
src/main/java/com/vaadin/recipes/recipe/scrollgridssidebyside/ScrollGridsSideBySide.java
src/main/java/com/vaadin/recipes/recipe/showsvg/ShowSvg.java

Using find . -type f -name "*.java"|xargs java -jar google-java-format-1.14.0-all-deps.jar --fix-imports-only --skip-sorting-imports  -r

chore: Remove unused imports

---

frontend/recipe/textfieldlabelleft/textfieldlabelleft.css

Due A11y input is slotted and container class name has changed amongst other things.

Fix the styles to work with Vaadin 22+

---

frontend/recipe/map-marker-drag-drop/map-marker-drag-drop.js
src/main/java/com/vaadin/recipes/recipe/mapmarkerdragdrop/CustomMap.java
src/main/java/com/vaadin/recipes/recipe/mapmarkerdragdrop/MapMarkerDragDrop.java

Adds a recipe that shows how to integrate the OpenLayers `Translate` interaction into the Vaadin Map component in order to move markers using drag&drop, and get notified about coordinate changes.

Add map marker drag drop recipe

---

src/main/java/com/vaadin/recipes/recipe/lazydetails/LazyDetails.java

Inspired by https://stackoverflow.com/questions/73410003/vaadin-23-lazy-loading-details-component

Show how to lazily initialize Details content

---

frontend/recipe/gridhyperlink/button-hyperlink.css
src/main/java/com/vaadin/recipes/recipe/gridhyperlinks/GridHyperlink.java

Example of how to create clickable link in Grid.  Typical for drill-down scenario.
Fixes #277

Example of hyperlinked grid

---

.vscode/settings.json
frontend/recipe/log-browser-errors/log-browser-errors.js
package-lock.json
package.json
src/main/java/com/vaadin/recipes/recipe/logbrowsererrors/LogBrowserErrors.java

This recipe shows a simple usage of the window event "error" and the Vaadin `@ClientCallable` annotation to allow logging of client side errors in the server log. 
- [ x] Feature
- [x ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ x] I have added a description following the guideline.
- [ x] The issue is created in the corresponding repository and I have referenced it.
- [x ] I have added tests to ensure my change is effective and works as intended.
- [x ] New and existing tests are passing locally with my change.
- [x ] I have performed self-review and corrected misspellings.

Added a recipe to demonstrate how to log client side errors on the server side.

---

src/main/java/com/vaadin/recipes/recipe/logbrowsererrors/LogBrowserErrors.java

Js module path fix and additional stylings / log clear button.

---

src/main/java/com/vaadin/recipes/recipe/multivalidator/MultiValidator.java
src/main/java/com/vaadin/recipes/recipe/multivalidator/MultiValidatorView.java

Added MultiValidator recipe.
MultiValidator is a Validator class that can show all failing validations for a field at once instead of stopping at the first Validator that fails.
See Issue [How do I display more than one validation message at a time?](https://github.com/vaadin/cookbook/issues/292)
- [NA] New and existing tests are passing locally with my change.

Added MultiValidator recipe.

---

src/main/java/com/vaadin/recipes/recipe/stickyvirtuallist/StickyVirtualListView.java

This adds a recipe with a solution to display sticky headers in the VirtualList.

feat: add recipe for sticky virtual list

---

src/main/java/com/vaadin/recipes/recipe/hostname/Hostname.java

Demonstrates several ways of getting host name in a Vaadin app.

Recipe: How to get the server host name in Vaadin app.

---

src/main/java/com/vaadin/recipes/recipe/treegridwithicons/TreeGridWithIcons.java

Without this fix caret is not showing

fix: Property binding should be ".leaf" instead "leaf"

---

pom.xml
src/main/java/com/vaadin/recipes/recipe/gridrecord/GridRecord.java

Improved example with add-on that properly supports records

Records in grid update

---

src/main/java/com/vaadin/recipes/recipe/scrolltoitemintreegrid/ScrollToItemInTreeGrid.java

No new dependencies. ScrollToItemInTreeGrid was broken and is now fixed.
Fixes # (issue)
ScrollToItemInTreeGrid

Adapt ScrollToItemInTreeGrid to Vaadin 24.
